config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  namespace :admin do
    root :to=> "welcome#contacts"
    resources :products
    resources :news
    resources :users do
      patch 'update_mailing_status' => 'users#update_mailing_status'
    end

  end

  resources :products, only: [:show, :index] do
    get 'biscuits', :on => :collection
    get 'puff_product', :on => :collection
    get 'cake', :on => :collection
    get 'desert', :on => :collection

  end
  resources :news, only: [:show, :index]
  resource :search, only: [:show, :create]
  resources :users, only: [:show]

  root 'welcome#index'
  get 'welcome/contacts'
  get 'welcome/about_company'
  post 'sending_email' => 'product_mailer#sending_email', as: :sending_email

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  include PgSearch::Model
end

app/models/news.rb
class News < ApplicationRecord
  paginates_per 10

  validates :title, presence: true
  validates :body, presence: true
  validates_length_of :title, :maximum => 60
  validates_length_of :body, :maximum => 500


  mount_uploader :title_image, ImageUploader

end

app/models/product.rb
# t.string "weight"
# t.integer "category", default: 0
# t.datetime "created_at", precision: 6, null: false
# t.datetime "updated_at", precision: 6, null: false
# t.string "image"
# t.text "description"



class Product < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_name, against: :name

  paginates_per 16

  validates :name, presence: true
  validates :image, presence: true
  validates :weight, presence: true
  validates :description, presence: true
  validates_length_of :name, :maximum => 40
  validates_length_of :description, :maximum => 200
  validates_length_of :weight, :maximum => 5

  mount_uploader :image, ImageUploader

  enum category: ['Печенье', 'Слойка', 'Торт', 'Пирожное']

  scope :desert, -> { where(category: 'Пирожное') }
  scope :cake, -> { where(category: 'Торт') }
  scope :puff_product, -> { where(category: 'Слойка') }
  scope :biscuits, -> { where(category: 'Печенье') }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!, only: [:new, :update, :destroy, :edit, :create]
  before_action :check_admin

    layout "admin"

  protected

  def check_admin
    redirect_to root_path, alert: "У вас нет доступа к этой странице" unless current_user.admin?
  end
  def after_sign_in_path_for(resource)
    if current_user.admin?
      redirect_to admin_products_path
    else
      redirect_to root_path
    end
  end

end

app/controllers/admin/news_controller.rb
class Admin::NewsController < Admin::BaseController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  def index
    @news = News.all.order('created_at desc').page(params[:page])
  end

  def show
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)

    if @news.save
      flash[:notice] = 'Успешно создана'
      redirect_to [:admin, @news]
      # status_notification = SendingOfLetters.new(@news).call
      # notification(status_notification)
    else
      flash[:error] = 'Произошла ошибка, запись не создана'
      render :new
    end
  end

  def edit
  end

  def update
    if @news.update(news_params)
      flash[:notice] = 'Запись успешно обновлена'
      redirect_to [:admin, @news]
    else
      flash[:error] = 'Произошла ошибка, запись не создана'
      render :edit
    end
  end

  def destroy
    @news.destroy
    flash[:notice] = 'Запись успешно удалена'
    redirect_to admin_news_index_path
  end

  private

  def notification(status)
    status ? flash[:notice] = 'Рассылка выполнена' : flash[:error] = 'Произошла ошибка, почта не отправлены'
  end

  def set_news
    @news = News.find(params[:id])
  end

  def news_params
    params.require(:news).permit(:title, :body, :title_image)
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all.order(:name).page(params[:page])
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = 'Создана новая позиция'
      redirect_to [:admin, @product]
      # status_notification = SendingOfLetters.new(@product).call
      # notification(status_notification)
    else
      flash[:alert] = 'Произошла ошибка, запись не создана'
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:notice] = 'Запись успешно обновлена'
      redirect_to [:admin, @product]
    else
      flash[:error] = 'Произошла ошибка, запись не обновлена'
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:notice] = 'Запись успешно удалена'
    redirect_to admin_products_path
  end

  private

  def notification(status)
    status ? flash[:notice] = 'Рассылка выполнена' : flash[:error] = 'Произошла ошибка, почта не отправлены'
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :weight, :category, :image, :description)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  skip_before_action :verify_authenticity_token
  before_action :set_user, only: [:show, :edit, :update, :destroy, :update_mailing_status]

  def index
    index_users_list
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to [:admin, @user]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to [:admin, @user]
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  def update_mailing_status
    @user.update(mailing_status: params[:mailing_status])
    index_users_list

    respond_to do |format|
      format.html { render template: 'admin/users/update_mailing_status', locals: { users: @users } }
    end
  end

  private

  def index_users_list
    @users = User.order('mailing_status ASC, email ASC')
  end


  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :id, :email, :mailing_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def after_sign_in_path_for(_resource)
  if current_user.admin?
    admin_products_path
  else
    root_path
  end
end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = News.all.order('created_at desc').page(params[:page])
  end

  def show
    @news = News.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  def index
    @products = Product.all.order(:name).page(params[:page])
  end

  def show
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :weight, :category, :image, :description)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def show
    @name = params[:name]
    @name.strip if @name.present?
    @products = Product.search_name(@name)
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about_company
  end

  def contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper

  def mailing_status_checked(user)
    user.mailing_status.present? ? 'checked' : ''
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/news/_news.html.erb
<tr>
  <td><%= news.title %></td>
  <td><%= link_to 'Показать', [:admin, news] %></td>
  <td><%= link_to 'Редактировать', edit_admin_news_path(news) %></td>
  <td><%= link_to 'Удалить', [:admin, news], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/news/index.html.erb
<h2 class="text-center">Новости</h2>
<div class="container">
  <div class="row">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Название</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @news %>
      </tbody>
    </table>
    <div class="col-xs-12 col-sm-12 padding">
      <%= link_to "Добавить новость", new_admin_news_path, :class=>"btn btn-info" %>
    </div>
    <%= paginate @news %>
  </div>
</div>

app/views/admin/news/show.html.erb
<br><br>
<div class="container">
  <div class="row">
    <div class="col-md-7" id="newsDescription">
      <h4 class="text-center"><%= @news.title if @news.title.present? %></h4>
      <div>
        <p class="lead"><%= @news.body %></p>
      </div>
      <div class="text-right" id="newsDataTime">
        <p>Добавлена: <%= @news.created_at.strftime("%T %D") %></p>
      </div>
      <div class="col-xs-12 col-sm-12 padding text-center" id="btn-master">
        <%= link_to 'Редактировать', edit_admin_news_path(@news), :class=>"btn" %>
      </div>
      <div class="col-xs-12 col-sm-12 padding text-center" id="btn-master">
        <%= link_to 'Назад', admin_news_index_path, :class=>"btn" %>
      </div>
    </div>
    <div class="col-md-5" id="newsShowImg">
      <%= image_tag @news.title_image.url(:large) if @news.title_image? %>
    </div>
  </div>
</div>

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= link_to 'Показать', [:admin, product] %></td>
  <td><%= link_to 'Редактировать', edit_admin_product_path(product) %></td>
  <td><%= link_to 'Удалить', [:admin, product], method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/products/index.html.erb
<h2 class="text-center">Вся продукция</h2>
<div class="container">
  <div class="row">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Название</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @products %>
      </tbody>
    </table>
    <div class="col-xs-12 col-sm-12 padding">
      <%= link_to "Новая позиция", new_admin_product_path, :class=>"btn btn-info" %>
    </div>
    <%= paginate @products %>
  </div>
</div>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.email %></td>
  <td>
    <label class="switch">
      <input type="checkbox" class='user-check-box' id="check_<%= user.id %>" type="checkbox" <%= mailing_status_checked(user) %>>
      <span class="slider round"></span>
    </label>
  </td>
  <td><%= link_to 'Показать', [:admin, user] %></td>
  <td><%= link_to 'Редактировать', edit_admin_user_path(user) %></td>
  <td><%= link_to 'Удалить', [:admin, user], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/users/update_mailing_status.html.erb
<%= render @users %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Мастер кондитерские изделия</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  </head>
  <body>
  <div class="fixed-top">
    <div class="row">
      <div class="container-fluid" id="navPanel">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon" style="font-size: 2em;"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <% if current_user %>
                <% if current_user.admin? %>
                  <%= link_to "Администратор", admin_products_path, :class=>"nav-link" %>
                <% else %>
                  <%= link_to "Главная", root_path, :class=>"nav-link" %>
                <% end %>
              <% else %>
                <%= link_to "Главная", root_path, :class=>"nav-link" %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "Каталог", products_path, :class=>"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Новости", news_index_path, :class=>"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Про нас", welcome_about_company_path, :class=>"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Контакты", welcome_contacts_path, :class=>"nav-link" %>
            </li>
            <li class="nav-item">
              <% if current_user %>
                <%= link_to "Выйти", destroy_user_session_path, method: :delete, :class=>"nav-link" %>
              <% else %>
                <%= link_to "Войти", new_user_session_path, :class=>"nav-link" %>
              <% end %>
            </li>
            <li class="nav-item" id="e-mai">
              <%= link_to "Email: #{ current_user.email if current_user }", current_user.present? ? "#{user_path(current_user)}" : "", :class=>"nav-link" %>
            </li>
          </ul>
          <div class="text-right">
            <%= form_tag search_path, method: :get do %>
              <%= text_field_tag :name, "", :class=>"search_panel" %>
              <%= submit_tag "Поиск", :class=>"btn-master-search" %>
            <% end %>
          </div>
        </div>
        </nav>
      </div>
    </div>
  </div>
  <div class="carousel slide" data-ride="carousel" id="slides">
    <ul class="carousel-indicators">
      <li data-target="#slides" data-slide-to="0" class="active"></li>
      <li data-target="#slides" data-slide-to="1"></li>
      <li data-target="#slides" data-slide-to="2"></li>
      <li data-target="#slides" data-slide-to="3"></li>
      <li data-target="#slides" data-slide-to="4"></li>
    </ul>

    <div class="carousel-inner" id="carouselDiv">
      <div class="carousel-item active text-center" id="carouselImg2">
        <%= image_tag("img/master_head2.jpg") %>
      </div>
      <div class="carousel-item" id="carouselImg">
        <%= image_tag("img/berry152.jpg") %>
          <div class="carousel-caption" id=carousel2>
          <h3>Начинки продукции "ТМ Мастер" делаются только из свежих и натуральных ягод и фруктов</h3>
        </div>
      </div>
      <div class="carousel-item" id="carouselImg">
        <%= image_tag("img/muka82.jpg") %>
        <div class="carousel-caption3">
          <div class="container">
            <h3>Компания <strong>Мастер</strong> использует только высококачественное сырье лучших сертифицированых
              Украинских производителей. Качество входящей продукции прходит контроль на всех этапах -
              от получения сырья до хранения продукта на складе.</h3>
          </div>
        </div>

      </div>
      <div class="carousel-item" id="carouselImg">
        <%= image_tag("img/povar.jpg") %>
          <div class="carousel-caption3 text-center" id="carousel4">
            <h3>
              Кондитеры, технологи, пекари, упаковщики - это команда профессионалов,
              в которой каждый тщательно выполняет свою работу.
            </h3>
          </div>

      </div>
      <div class="carousel-item" id="carouselImg">
        <%= image_tag("img/zlaki2.jpg") %>
          <div class="carousel-caption">
            <h3>Для приготовления Грильяжа, мы используем только отборные злаки</h3>
          </div>
      </div>
    </div>
  </div>

    <h1 class="notice"><%= notice %></h1>
    <h1 class="alert"><%= alert %></h1>

    <%= yield %>

    <footer class="container-fluid">
        <div class="row text-center">
          <div class="col-md-5 social padding">
            <h4>Контатктная информация</h4>
            <p>
              г. Харьков ул. Автогенная 10<br>
              Тел: +380504023130<br>
              master2009sales@gmail.com
            </p>
            <p>&copy All rights reserved</p>
          </div>
          <div class="col-md-7" id="footerImg">
            <%= image_tag("img/master_title3.jpg") %>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/products/biscuits.html.erb
<div class="container-fluid">
  <div class="row" >
    <ul class="nav nav-tabs text-center justify-content-left bg-light" id="navTabs">
      <li class="nav-item">
        <%= link_to "Вся продукция", products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Торты", cake_products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Пирожные", desert_products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Слойка", puff_product_products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Печенье", biscuits_products_path, :class=>"nav-link active" %>
      </li>
    </ul>
  </div>
</div>
<br><br>
<div class="container">
  <div class="row">
    <%= render Product.all.biscuits %>
  </div>
</div>

app/views/products/cake.html.erb
<div class="container-fluid">
  <div class="row" >
    <ul class="nav nav-tabs text-center justify-content-left bg-light" id="navTabs">
      <li class="nav-item">
        <%= link_to "Вся продукция", products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Торты", cake_products_path, :class=>"nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Пирожные", desert_products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Слойка", puff_product_products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Печенье", biscuits_products_path, :class=>"nav-link" %>
      </li>
    </ul>
  </div>
</div>
<br><br>
<div class="container">
  <div class="row">
    <%= render Product.all.cake %>
  </div>
</div>

app/views/products/desert.html.erb
<div class="container-fluid">
  <div class="row" >
    <ul class="nav nav-tabs text-center justify-content-left bg-light" id="navTabs">
      <li class="nav-item">
        <%= link_to "Вся продукция", products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Торты", cake_products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Пирожные", desert_products_path, :class=>"nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Слойка", puff_product_products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Печенье", biscuits_products_path, :class=>"nav-link" %>
      </li>
    </ul>
  </div>
</div>
<br><br>
<div class="container">
  <div class="row">
    <%= render Product.all.desert %>
  </div>
</div>

app/views/products/index.html.erb
<div class="container-fluid">
  <div class="row" >
    <ul class="nav nav-tabs text-center justify-content-left bg-light" id="navTabs">
      <li class="nav-item">
        <%= link_to "Вся продукция", products_path, :class=>"nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Торты", cake_products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Пирожные", desert_products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Слойка", puff_product_products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Печенье", biscuits_products_path, :class=>"nav-link" %>
      </li>
    </ul>
  </div>
</div>
<br><br>
<div class="container">
  <div class="row">
    <%= render @products%>
  </div>
</div>
<%= paginate @products %>

app/views/products/puff_product.html.erb
<div class="container-fluid">
  <div class="row" >
    <ul class="nav nav-tabs text-center justify-content-left bg-light" id="navTabs">
      <li class="nav-item">
        <%= link_to "Вся продукция", products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Торты", cake_products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Пирожные", desert_products_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Слойка", puff_product_products_path, :class=>"nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Печенье", biscuits_products_path, :class=>"nav-link" %>
      </li>
    </ul>
  </div>
</div>
<br><br>
<div class="container">
  <div class="row">
    <%= render Product.all.puff_product %>
  </div>
</div>

app/views/searches/show.html.erb
<div class="container">
  <div class="row">
    <% if !@products.empty? %>
      <% @products.each do |product|%>
        <div class="col-md-3" id="newsIndexImg">
          <%= image_tag product.image.url(:menu_img) if product.image? %>
        </div>
        <div class="col-md-9" id="newsIndex">
          <h4 class="text-center text-truncate"><%= link_to product.name, product_path(product) %></h4>
          <p class="lead" id="news_index"><%= product.description %></p>
          <div class="col-xs-12 col-sm-12 padding" id="btn-master">
            <% if current_user.present? %>
              <% if current_user.admin? %>
                <%= link_to "Редактировать", edit_admin_product_path(product), :class=>"btn btn-light" %>
              <% end %>
            <% end %>
            <%= link_to "Посмотреть", product_path(product), :class=>"btn btn-light" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <hr>
        <div id="noResult">
          <h4>Не найдено ни одной позици по Вашему запросу</h4>
        </div>
      <hr>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
 <div class="fixed-wrap">
  <div id="fixed3"></div>
</div>
<br><br><br>
<div class="container-fluid">
  <div class="row">
    <div>
      <div>
        <% if News.all.empty? %>
          <p>Пока нет ничего нового</p>
        <% else %>
          <div class="container">
            <div class="row">
              <div class="col-md-3" id="newsIndexImg">
                <%= image_tag News.last.title_image.url(:menu_img) if News.last.title_image? %>
              </div>
              <div class="col-md-9" id="newsIndex">
                <h4 class="text-center text-truncate"><%= link_to News.last.title, news_path(News.last) %></h4>
                <div id="news_index">
                  <p><%= News.last.body %></p>
                </div>
                <div class="text-right" id="newsDataTime">
                  <p>Добавлена: <%= News.last.created_at.strftime("%T %D") %></p>
                </div>
                <div class="col-xs-12 col-sm-12 padding" id="btn-master">
                  <%= link_to "Подробнее", news_path(News.last), :class=>"btn btn-light" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="border-bottom-red"></div>
<br><br><br>
<div class="container">
  <h2 class="text-center" id="borderBottom">Наша продукция</h2><br>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-4" id="rootMenu">
      <%= link_to image_tag("img/desert.jpg", :class=>"img-fluid img-thumbnail"), desert_products_path%>
      <div class="root-menu-text">
        <h3><%= link_to "Пирожные", desert_products_path %></h3>
      </div>
    </div>
    <div class="col-md-4" id="rootMenu">
      <%= link_to image_tag("img/puff_product.jpg", :class=>"img-fluid img-thumbnail"), puff_product_products_path %>
      <div class="root-menu-text">
        <h3><%= link_to "Слоеные изделия", puff_product_products_path %></h3>
      </div>
    </div>
    <div class=col-md-2></div>
    <div class=col-md-2></div>
    <div class="col-md-4" id="rootMenu">
      <%= link_to image_tag("img/tiramisu.jpg", :class=>"img-fluid img-thumbnail"), cake_products_path %>
      <div class="root-menu-text">
        <h3><%= link_to "Торты", cake_products_path %></h3>
      </div>
    </div>
    <div class="col-md-4" id="rootMenu">
      <%= link_to image_tag("img/biscuits.jpg", :class=>"img-fluid img-thumbnail"), biscuits_products_path %>
      <div class="root-menu-text">
        <h3><%= link_to "Печенье", biscuits_products_path %></h3>
      </div>
    </div>
    <div class=col-md-2></div>
    <div class="col-xs-12 col-sm-12 text-center" id="btn-master">
      <br>
        <%= link_to "Посмотреть весь ассортимент",  products_path, :class=>"btn btn-lg" %>
    </div>
  </div>
</div>
  <br><br><br>
  <div class="fixed-wrap">
    <div id="fixed2">
      <div class="container">
        <div class="row">
          <div class="col-md-5 text-center" id="partner">
            <p>Наша компания приглашает к сотрудничеству магазины, кафе, оптовые базы, дистрибьюторские компании, торговые компании.
            Работаем без выходных. Для каждого клиента персональный подход и условия. Более детальная информация по
            телефону: +380504023130</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br><br><br>
  <div class="container-fluid padding">
    <div class="row padding">
      <div class="offset-lg-2 col-lg-4">
        <h2>Немного про нас:</h2>
        <p><strong>Мастер</strong>
          – украинская кондитерская компания, которая изготовляет более
          100 видов высококачественных кондитерских изделий. Компания была основана в 2009 году. Основные мощности
          компании Мастер расположены в Харькове.
        </p>
        <p>Компания прикладывает максимум усилий, что бы продукция имела безупречное качество, начиная с отбора
          ингридиентов, профессионального подхода квалифицированных кондитеров - до сохранения и доставки готовых
          кондитерских изделий покупателю.
          </p>
        <div class="col-xs-12 col-sm-12" id="btn-master">
            <%= link_to "Читать далее",  welcome_about_company_path, :class=>"btn btn-light" %><br><br><br>
        </div>
      </div>
      <div class="col-md-5">
        <%= image_tag("img/master_title.jpg", :class=>"about-company-img") %>
      </div>
    </div>
  </div>
  <div class="fixed-wrap">
    <div id="fixed">
    </div>
  </div>
  <br><br><br><br><br>
  <div class="container">
    <h2 class="text-center" id="borderBottom">Преимущества компании</h2>
  </div>
  <br><br><br>
  <div class="container padding">
    <div class="row padding">
      <div class="col-md-4" id="cardBox">
        <div class="card">
          <%= image_tag("img/zdanie.jpg", :class=>"card-img-top") %>
          <div class="card-body">
            <h4 class="card-title">Собственное помещение</h4>
            <p class="card-text">Одним из достижений компании Мастер стало приобретение
              собственного производственного помещения. Это позволило модернизировать производство и
              значительно увеличить объемы выпускаемой продукции.
            </p>
          </div>
        </div>
      </div>
      <div class="col-md-4" id="cardBox">
        <div class="card">
          <%= image_tag("img/laboratory.jpg", :class=>"card-img-top") %>
          <div class="card-body">
            <h4 class="card-title">Собственная лаборатория</h4>
            <p class="card-text">На предприятии постоянно действует лаборатория по проверке качества
              входящего сырья и соответствия изготовленной продукции стандартам и нормам,
              установленным законодательством.
            </p>
          </div>
        </div>
      </div>
      <div class="col-md-4" id="cardBox">
        <div class="card">
          <%= image_tag("img/konditer.jpg", :class=>"card-img-top") %>
          <div class="card-body">
            <h4 class="card-title">Высокая квалификаци</h4>
            <p class="card-text">Предприятие заботится о повышении квалификации
              сотрудников:для ведущих специалистов проводятся различные семинары и тренинги,
              направленные на улучшение вкусовых качеств нашей продукции.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>